// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKINxhm8hWKqN_LfWrbzJG9z2-JQeGEu0',
    appId: '1:267707321556:web:5d89bc1efcc04913637f41',
    messagingSenderId: '267707321556',
    projectId: 'news-app-57503',
    authDomain: 'news-app-57503.firebaseapp.com',
    storageBucket: 'news-app-57503.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6U4m-YQ9bY0CwxWZ4tyOM7srjCZ60_7o',
    appId: '1:267707321556:android:c2ad32b16a4d97b1637f41',
    messagingSenderId: '267707321556',
    projectId: 'news-app-57503',
    storageBucket: 'news-app-57503.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB45gULeVSAKlj0g2bSFPBTUiQiu330Yxc',
    appId: '1:267707321556:ios:a536ac43d675468c637f41',
    messagingSenderId: '267707321556',
    projectId: 'news-app-57503',
    storageBucket: 'news-app-57503.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB45gULeVSAKlj0g2bSFPBTUiQiu330Yxc',
    appId: '1:267707321556:ios:a536ac43d675468c637f41',
    messagingSenderId: '267707321556',
    projectId: 'news-app-57503',
    storageBucket: 'news-app-57503.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKINxhm8hWKqN_LfWrbzJG9z2-JQeGEu0',
    appId: '1:267707321556:web:f3976615333a7ba2637f41',
    messagingSenderId: '267707321556',
    projectId: 'news-app-57503',
    authDomain: 'news-app-57503.firebaseapp.com',
    storageBucket: 'news-app-57503.appspot.com',
  );
}
